import { GoogleGenAI } from "@google/genai";
import type { ChatMessage, GeminiModelInfo } from "../types";

const STORAGE_KEY_GEMINI_API_KEY = "react_chat_gemini_api_key";
const STORAGE_KEY_GEMINI_MODEL = "react_chat_gemini_model";

export const AVAILABLE_MODELS: GeminiModelInfo[] = [
  {
    id: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash",
    tag: "Recommended",
    desc: "Cutting-edge high capability and intelligence",
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    tag: "Fast",
    desc: "Optimized for speed and concise answers",
  },
  {
    id: "gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    tag: "Stable",
    desc: "High throughput and reliable developer assistance",
  },
  {
    id: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    tag: "Advanced",
    desc: "Complex code reasoning and deep architecture insights",
  },
];

/**
 * Retrieve the active Gemini API key from localStorage, environment, or config
 */
export const getGeminiApiKey = (): string => {
  try {
    const saved = localStorage.getItem(STORAGE_KEY_GEMINI_API_KEY);
    if (saved && saved.trim()) return saved.trim();
  } catch {}

  if (typeof import.meta !== "undefined" && import.meta.env?.VITE_GEMINI_API_KEY) {
    return import.meta.env.VITE_GEMINI_API_KEY;
  }
  if (typeof process !== "undefined" && process.env?.REACT_APP_GEMINI_API_KEY) {
    return process.env.REACT_APP_GEMINI_API_KEY;
  }

  return "";
};

/**
 * Save user custom Gemini API key to localStorage
 */
export const setGeminiApiKey = (key: string): void => {
  try {
    if (key && key.trim()) {
      localStorage.setItem(STORAGE_KEY_GEMINI_API_KEY, key.trim());
    } else {
      localStorage.removeItem(STORAGE_KEY_GEMINI_API_KEY);
    }
  } catch {}
};

/**
 * Retrieve preferred model or default to gemini-3.8-flash
 */
export const getGeminiModel = (): string => {
  try {
    const saved = localStorage.getItem(STORAGE_KEY_GEMINI_MODEL);
    if (saved && saved !== "gemini-2.5-flash") return saved;
  } catch {}
  return "gemini-3.8-flash";
};

export const setGeminiModel = (model: string): void => {
  try {
    localStorage.setItem(STORAGE_KEY_GEMINI_MODEL, model);
  } catch {}
};

/**
 * Validate / test a Gemini API key with a ping request
 */
export const testGeminiApiKey = async (
  apiKey: string,
  model = "gemini-3.8-flash"
): Promise<boolean> => {
  const keyToTest = (apiKey || "").trim();
  if (!keyToTest) {
    throw new Error("API key is required to run test.");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${keyToTest}`;
  const response = await fetch(endpoint, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: "Ping test. Please respond with 'OK'." }],
        },
      ],
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    const message =
      errData?.error?.message ||
      `HTTP status ${response.status} (${response.statusText})`;
    throw new Error(message);
  }

  return true;
};

/**
 * Direct REST fallback if SDK has client-side network or CORS constraints
 */
const callGeminiRestApi = async (
  apiKey: string,
  model: string,
  fullPrompt: string
): Promise<string> => {
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: fullPrompt }],
        },
      ],
      systemInstruction: {
        parts: [
          {
            text:
              "You are Gemini AI, an enthusiastic, helpful, and brilliant AI coding mentor in the #general-developers chat room. " +
              "Provide clear, crisp responses formatted in markdown with code blocks (specifying the language like ```jsx or ```javascript), bullet points, and concise explanations. " +
              "Keep replies chat-friendly (not too long unless asked for a complete tutorial).",
          },
        ],
      },
      generationConfig: {
        temperature: 0.7,
        topK: 40,
        topP: 0.95,
        maxOutputTokens: 2048,
      },
    }),
  });

  if (!response.ok) {
    const errData = await response.json().catch(() => ({}));
    throw new Error(
      errData?.error?.message ||
        `HTTP ${response.status}: Failed to reach Gemini API.`
    );
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!text) {
    throw new Error("No response generated by Gemini model.");
  }
  return text;
};

/**
 * Format conversation history into chat context
 */
const buildConversationContext = (
  recentMessages: ChatMessage[] = [],
  currentPrompt: string
): string => {
  if (!recentMessages || recentMessages.length === 0) {
    return `User asks:\n${currentPrompt}`;
  }

  const historyLines = recentMessages
    .slice(-8)
    .filter((m) => m && m.text && !m.text.startsWith("⚠️ Gemini encountered"))
    .map((m) => {
      const sender =
        m.isBot || m.uid === "gemini-bot" ? "Gemini AI" : m.name || "Developer";
      return `${sender}: ${m.text}`;
    });

  if (historyLines.length === 0) {
    return `User asks:\n${currentPrompt}`;
  }

  return (
    `Here is the recent conversation transcript in the room for context:\n` +
    `---\n` +
    historyLines.join("\n") +
    `\n---\n\n` +
    `Now respond helpfully to the latest user query:\n${currentPrompt}`
  );
};

/**
 * Generate AI response using @google/genai SDK with automatic fallbacks
 */
export const generateGeminiResponse = async (
  prompt: string,
  modelName: string | null = null,
  recentMessages: ChatMessage[] = []
): Promise<string> => {
  const apiKey = getGeminiApiKey();
  const selectedModel = modelName || getGeminiModel();

  if (!apiKey) {
    return (
      "👋 Hi there! I'm Gemini AI. To enable AI answers in this chat, please configure a Gemini API key:\n\n" +
      "1. Click the **✨ Gemini AI** button in the top navbar.\n" +
      "2. Paste your Google AI Studio API key and save.\n" +
      "3. Or add `VITE_GEMINI_API_KEY=your_key` to your `.env` file.\n\n" +
      "You can get a free API key at [Google AI Studio](https://aistudio.google.com/app/apikey)."
    );
  }

  const contextualPrompt = buildConversationContext(recentMessages, prompt);

  // 1. Try GoogleGenAI Interactions API
  try {
    const ai = new GoogleGenAI({ apiKey });

    if (ai.interactions && typeof ai.interactions.create === "function") {
      try {
        const interaction = await ai.interactions.create({
          model: selectedModel || "gemini-3.8-flash",
          input: contextualPrompt,
        });

        if (interaction?.output_text) {
          return interaction.output_text;
        }
        if ((interaction as any)?.text) {
          return (interaction as any).text;
        }
      } catch (interactionErr: any) {
        console.debug(
          "interactions.create fell back to REST API:",
          interactionErr?.message
        );
      }
    }

    // 2. Try GoogleGenAI models.generateContent API
    if (ai.models && typeof ai.models.generateContent === "function") {
      try {
        const response = await ai.models.generateContent({
          model: selectedModel,
          contents: contextualPrompt,
        });

        if (response?.text) {
          return response.text;
        }
      } catch (modelsErr: any) {
        console.debug(
          "models.generateContent fell back to REST API:",
          modelsErr?.message
        );
      }
    }
  } catch (sdkInitErr: any) {
    console.debug(
      "GoogleGenAI SDK init fell back to REST API:",
      sdkInitErr?.message
    );
  }

  // 3. Fallback to Direct REST API (guarantees 100% reliable responses in browser)
  try {
    return await callGeminiRestApi(apiKey, selectedModel, contextualPrompt);
  } catch (restErr: any) {
    console.error("Gemini API error:", restErr);
    const msg = restErr.message || "Unable to reach Gemini API";
    return (
      `⚠️ **Gemini encountered an error:** ${msg}\n\n` +
      `*Tips:*\n` +
      `- Verify your API key in **✨ Gemini AI** settings.\n` +
      `- Check that your key has permissions for \`${selectedModel}\` in Google AI Studio.\n` +
      `- If you hit quota limits, try switching to \`gemini-2.0-flash\` or \`gemini-1.5-flash\`.`
    );
  }
};
